#Imagen de base oficial de NGINX
FROM nginx:alpine

#Copiar los archivos de la web al directorio publico de NGINX
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
