# Imagen base oficial de NGINX
FROM nginx:alpine

# Copiar los archivos de la web al directorio público de NGINX
COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css